DEF NAME_BUFFER_LENGTH          EQU 16

DEF MAX_PLAYER_NAME_LENGTH      EQU 6   * 2
DEF MAX_DECK_NAME_LENGTH        EQU 20  * 1 ; note that its unit is byte!

DEF NAMING_SCREEN_BUFFER_LENGTH EQU 24

; wWhichKeyboard constants
DEF UPPERCASE_KEYBOARD  EQU 0
DEF LOWERCASE_KEYBOARD  EQU 1
DEF ACCENTS_KEYBOARD    EQU 2
